-- =====================================================================
-- SocialSales OS — Phase 1 Foundation Schema
-- Multi-tenant model: every business = one "workspace".
-- All tenant-scoped tables carry workspace_id and are protected by RLS
-- so that Postgres itself — not application code — enforces isolation.
-- =====================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------
-- profiles: 1:1 with auth.users, holds display info
-- ---------------------------------------------------------------------
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  avatar_url text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create policy "profiles_select_own"
  on public.profiles for select
  using (id = auth.uid());

create policy "profiles_update_own"
  on public.profiles for update
  using (id = auth.uid());

-- Auto-create a profile row whenever a new auth user signs up.
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer set search_path = public;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ---------------------------------------------------------------------
-- workspaces: the tenant boundary. Every business = one workspace.
-- ---------------------------------------------------------------------
create type public.workspace_industry as enum (
  'clinic', 'real_estate', 'training_center', 'instagram_store', 'restaurant', 'other'
);

create table public.workspaces (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  industry public.workspace_industry not null default 'other',
  owner_id uuid not null references auth.users(id) on delete cascade,
  meta_pixel_id text, -- merchant-owned Meta Pixel ID, never generated by us
  created_at timestamptz not null default now()
);

alter table public.workspaces enable row level security;

-- ---------------------------------------------------------------------
-- memberships: many-to-many between users and workspaces, with role.
-- This is the join table every RLS policy below relies on.
-- ---------------------------------------------------------------------
create type public.member_role as enum ('owner', 'admin', 'agent');

create table public.workspace_members (
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.member_role not null default 'agent',
  created_at timestamptz not null default now(),
  primary key (workspace_id, user_id)
);

alter table public.workspace_members enable row level security;

-- Helper: is the current user a member of the given workspace?
create function public.is_workspace_member(target_workspace_id uuid)
returns boolean as $$
  select exists (
    select 1 from public.workspace_members
    where workspace_id = target_workspace_id
      and user_id = auth.uid()
  );
$$ language sql security definer stable set search_path = public;

-- Helper: does the current user have admin/owner rights on the workspace?
create function public.is_workspace_admin(target_workspace_id uuid)
returns boolean as $$
  select exists (
    select 1 from public.workspace_members
    where workspace_id = target_workspace_id
      and user_id = auth.uid()
      and role in ('owner', 'admin')
  );
$$ language sql security definer stable set search_path = public;

create policy "workspaces_select_member"
  on public.workspaces for select
  using (public.is_workspace_member(id));

create policy "workspaces_insert_owner"
  on public.workspaces for insert
  with check (owner_id = auth.uid());

create policy "workspaces_update_admin"
  on public.workspaces for update
  using (public.is_workspace_admin(id));

create policy "members_select_same_workspace"
  on public.workspace_members for select
  using (public.is_workspace_member(workspace_id));

create policy "members_insert_admin"
  on public.workspace_members for insert
  with check (public.is_workspace_admin(workspace_id) or user_id = auth.uid());

create policy "members_update_admin"
  on public.workspace_members for update
  using (public.is_workspace_admin(workspace_id));

create policy "members_delete_admin"
  on public.workspace_members for delete
  using (public.is_workspace_admin(workspace_id));

-- Automatically add the creator of a workspace as its owner member.
create function public.handle_new_workspace()
returns trigger as $$
begin
  insert into public.workspace_members (workspace_id, user_id, role)
  values (new.id, new.owner_id, 'owner');
  return new;
end;
$$ language plpgsql security definer set search_path = public;

create trigger on_workspace_created
  after insert on public.workspaces
  for each row execute procedure public.handle_new_workspace();

-- ---------------------------------------------------------------------
-- leads: the CRM core. Scoped to workspace_id, protected by RLS.
-- ---------------------------------------------------------------------
create type public.lead_status as enum (
  'new', 'contacted', 'interested', 'negotiating', 'won', 'lost'
);

create table public.leads (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  full_name text not null,
  phone text,
  email text,
  source text,          -- e.g. 'instagram', 'facebook_ad', 'whatsapp'
  campaign_id uuid,      -- fk added in Phase 5 migration once campaigns exist
  status public.lead_status not null default 'new',
  assigned_to uuid references auth.users(id),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index leads_workspace_idx on public.leads (workspace_id);
create index leads_status_idx on public.leads (workspace_id, status);
create index leads_assigned_idx on public.leads (workspace_id, assigned_to);

alter table public.leads enable row level security;

create policy "leads_select_member"
  on public.leads for select
  using (public.is_workspace_member(workspace_id));

create policy "leads_insert_member"
  on public.leads for insert
  with check (public.is_workspace_member(workspace_id));

create policy "leads_update_member"
  on public.leads for update
  using (public.is_workspace_member(workspace_id));

create policy "leads_delete_admin"
  on public.leads for delete
  using (public.is_workspace_admin(workspace_id));

-- Keep updated_at fresh on every write.
create function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger leads_set_updated_at
  before update on public.leads
  for each row execute procedure public.set_updated_at();
