-- =====================================================================
-- SocialSales OS — Phase 1 Foundation Schema
-- Multi-tenant model: every business = one "workspace".
-- All tenant-scoped tables carry workspace_id and are protected by RLS
-- so that Postgres itself — not application code — enforces isolation.
-- =====================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------
-- profiles: 1:1 with auth.users, holds display info
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  avatar_url text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  using (id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  using (id = auth.uid());

-- Auto-create a profile row whenever a new auth user signs up.
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ---------------------------------------------------------------------
-- workspaces: the tenant boundary. Every business = one workspace.
-- ---------------------------------------------------------------------
do $$ begin
  create type public.workspace_industry as enum (
  'clinic', 'real_estate', 'training_center', 'instagram_store', 'restaurant', 'other'
);
exception when duplicate_object then null;
end $$;

create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  industry public.workspace_industry not null default 'other',
  owner_id uuid not null references auth.users(id) on delete cascade,
  meta_pixel_id text, -- merchant-owned Meta Pixel ID, never generated by us
  created_at timestamptz not null default now()
);

alter table public.workspaces enable row level security;

-- Safety net: `workspaces` may already exist from an earlier partial
-- run with fewer columns than this definition — CREATE TABLE IF NOT
-- EXISTS above silently skips adding any of them in that case, so add
-- each one explicitly here too (harmless / no-op if already present).
alter table public.workspaces add column if not exists name text;
alter table public.workspaces add column if not exists slug text;
alter table public.workspaces add column if not exists industry public.workspace_industry not null default 'other';

-- Type-fix safety net: if `industry` already existed as a plain text
-- column (from before this schema existed), convert it to the proper
-- enum type now that the enum itself is guaranteed to exist above.
do $$ begin
  if (select data_type from information_schema.columns
      where table_schema = 'public' and table_name = 'workspaces' and column_name = 'industry') = 'text' then
    alter table public.workspaces alter column industry drop default;
    alter table public.workspaces
      alter column industry type public.workspace_industry using industry::public.workspace_industry;
    alter table public.workspaces alter column industry set default 'other'::public.workspace_industry;
    alter table public.workspaces alter column industry set not null;
  end if;
exception when others then
  raise notice 'Skipped industry type conversion: %', sqlerrm;
end $$;
alter table public.workspaces add column if not exists owner_id uuid references auth.users(id) on delete cascade;
alter table public.workspaces add column if not exists meta_pixel_id text;
alter table public.workspaces add column if not exists created_at timestamptz not null default now();

-- ---------------------------------------------------------------------
-- memberships: many-to-many between users and workspaces, with role.
-- This is the join table every RLS policy below relies on.
-- ---------------------------------------------------------------------
do $$ begin
  create type public.member_role as enum ('owner', 'admin', 'agent');
exception when duplicate_object then null;
end $$;

create table if not exists public.workspace_members (
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.member_role not null default 'agent',
  created_at timestamptz not null default now(),
  primary key (workspace_id, user_id)
);

alter table public.workspace_members enable row level security;

-- Safety net (same reasoning as workspaces above): add any inline
-- column that a pre-existing workspace_members table might be missing.
alter table public.workspace_members add column if not exists role public.member_role not null default 'agent';
alter table public.workspace_members add column if not exists created_at timestamptz not null default now();

-- Helper: is the current user a member of the given workspace?
create or replace function public.is_workspace_member(target_workspace_id uuid)
returns boolean as $$
  select exists (
    select 1 from public.workspace_members
    where workspace_id = target_workspace_id
      and user_id = auth.uid()
  );
$$ language sql security definer stable set search_path = public;

-- Helper: does the current user have admin/owner rights on the workspace?
create or replace function public.is_workspace_admin(target_workspace_id uuid)
returns boolean as $$
  select exists (
    select 1 from public.workspace_members
    where workspace_id = target_workspace_id
      and user_id = auth.uid()
      and role in ('owner', 'admin')
  );
$$ language sql security definer stable set search_path = public;

drop policy if exists "workspaces_select_member" on public.workspaces;
create policy "workspaces_select_member"
  on public.workspaces for select
  using (public.is_workspace_member(id));

drop policy if exists "workspaces_insert_owner" on public.workspaces;
create policy "workspaces_insert_owner"
  on public.workspaces for insert
  with check (owner_id = auth.uid());

drop policy if exists "workspaces_update_admin" on public.workspaces;
create policy "workspaces_update_admin"
  on public.workspaces for update
  using (public.is_workspace_admin(id));

drop policy if exists "members_select_same_workspace" on public.workspace_members;
create policy "members_select_same_workspace"
  on public.workspace_members for select
  using (public.is_workspace_member(workspace_id));

drop policy if exists "members_insert_admin" on public.workspace_members;
create policy "members_insert_admin"
  on public.workspace_members for insert
  with check (public.is_workspace_admin(workspace_id) or user_id = auth.uid());

drop policy if exists "members_update_admin" on public.workspace_members;
create policy "members_update_admin"
  on public.workspace_members for update
  using (public.is_workspace_admin(workspace_id));

drop policy if exists "members_delete_admin" on public.workspace_members;
create policy "members_delete_admin"
  on public.workspace_members for delete
  using (public.is_workspace_admin(workspace_id));

-- Automatically add the creator of a workspace as its owner member.
create or replace function public.handle_new_workspace()
returns trigger as $$
begin
  insert into public.workspace_members (workspace_id, user_id, role)
  values (new.id, new.owner_id, 'owner');
  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists on_workspace_created on public.workspaces;
create trigger on_workspace_created
  after insert on public.workspaces
  for each row execute procedure public.handle_new_workspace();

-- ---------------------------------------------------------------------
-- leads: the CRM core. Scoped to workspace_id, protected by RLS.
-- ---------------------------------------------------------------------
do $$ begin
  create type public.lead_status as enum (
  'new', 'contacted', 'interested', 'negotiating', 'won', 'lost'
);
exception when duplicate_object then null;
end $$;

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  full_name text not null,
  phone text,
  email text,
  source text,          -- e.g. 'instagram', 'facebook_ad', 'whatsapp'
  campaign_id uuid,      -- fk added in Phase 5 migration once campaigns exist
  status public.lead_status not null default 'new',
  assigned_to uuid references auth.users(id),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists leads_workspace_idx on public.leads (workspace_id);
create index if not exists leads_status_idx on public.leads (workspace_id, status);
create index if not exists leads_assigned_idx on public.leads (workspace_id, assigned_to);

alter table public.leads enable row level security;

drop policy if exists "leads_select_member" on public.leads;
create policy "leads_select_member"
  on public.leads for select
  using (public.is_workspace_member(workspace_id));

drop policy if exists "leads_insert_member" on public.leads;
create policy "leads_insert_member"
  on public.leads for insert
  with check (public.is_workspace_member(workspace_id));

drop policy if exists "leads_update_member" on public.leads;
create policy "leads_update_member"
  on public.leads for update
  using (public.is_workspace_member(workspace_id));

drop policy if exists "leads_delete_admin" on public.leads;
create policy "leads_delete_admin"
  on public.leads for delete
  using (public.is_workspace_admin(workspace_id));

-- Keep updated_at fresh on every write.
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists leads_set_updated_at on public.leads;
create trigger leads_set_updated_at
  before update on public.leads
  for each row execute procedure public.set_updated_at();
